---
- hosts: all
  become: true
  tasks:
  - include_vars: secrets.yml
  - git:
      repo: 'https://github.com/pretix/pretix.git'
      dest: /home/pretix/pretix
  - name: create folder for config
    file:  
      path: "{{ item }}"
      state: directory
      owner: 15371
      group: 15371
      mode: 0755
    with_items:
      - /home/pretix/etc/pretix
      - /var/pretix-data
  - name: copy plugins.txt
    copy:
      src: ./files/plugins.txt
      dest: /home/pretix/pretix/src/requirements/plugins.txt
      owner: pretix
      group: pretix
      mode: 0644
  - name: copy plugins.txt
    copy:
      src: ./files/Dockerfile
      dest: /home/pretix/pretix/Dockerfile
      owner: pretix
      group: pretix
      mode: 0644
  - name: create folder for config
    file:
      path: /var/postgres-data
      state: directory
      owner: pretix
      group: pretix
      mode: 0777
  - name: template pretix config
    template:
      src: ./templates/pretix.cfg.j2
      dest: /home/pretix/etc/pretix/pretix.cfg
      owner: 15371
      group: 15371
      mode: 0644
  - name: enable cron job for pretix maintenance
    cron:
      name: "pretix maintenance"
      minute: "15,45"
      job: "/usr/bin/docker exec web pretix cron"
  - name: run docker compose
    docker_service:
      project_name: "pretix"
      project_src: /home/pretix
      state: present
       

