---
- hosts: all
  become: true
  tasks:
  - include_vars: secrets.yml
  - name: install awscli
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - awscli
  - name: create folder for aws config
    file:
      path: "{{ item }}"
      state: directory
      owner: pretix
      group: pretix
      mode: 0777
    with_items:
      - /home/pretix/backups
      - /home/pretix/.aws
  - name: copy aws config
    template:
      src: ./templates/aws_config.j2
      dest: /home/pretix/.aws/config
      owner: pretix
      group: pretix
      mode: 0600
  - name: enable cron job for backup
    cron:
      name: "cron for postgres backup"
      minute: "0"
      hour: "5"
      job: "/usr/bin/docker exec -t -u postgres pretix_db_1 pg_dumpall -c > /home/pretix/backups/pretix_dump_`date +\\%d`.sql"
      user: "pretix"
  - name: enable cron job for s3 sync
    cron:
      name: "cron for backup s3 sync"
      minute: "0"
      hour: "6"
      job: "/usr/bin/aws s3 sync /home/pretix/backups s3://ec-nds-backups/Pretix-PostgreSQL-Backups"
      user: "pretix"
