---
- hosts: all
  become: true
  tasks:
  - name: download docker
    get_url:
      url: https://get.docker.com
      dest: /tmp/docker.sh
  - name: install docker
    command: "bash /tmp/docker.sh"
  - name: add user to docker group
    user:
      name: pretix
      groups: docker
      append: yes
  - name: download docker compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64" 
      dest: /usr/local/bin/docker-compose
  - name: make docker-compose executable
    file:
      path: /usr/local/bin/docker-compose
      mode: 0755
  - name: copy docker compose file to remote
    template:
      src: ./templates/docker-compose.yml.j2
      dest: /home/pretix/docker-compose.yml
      owner: pretix
      group: pretix
      mode: 0644