---
- hosts: all
  become: true
  tasks:
  - name: install nginx
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - nginx
  - name: copy nginx config
    copy:
      src: ./files/nginx.conf
      dest: /etc/nginx/sites-available/tickets.ec-niedersachsen.de
  - name: set symlink
    file:
      src: /etc/nginx/sites-available/tickets.ec-niedersachsen.de
      dest: /etc/nginx/sites-enabled/tickets.ec-niedersachsen.de
      state: link
  - name: remove default symlink
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  - name: start and enable nginx
    service:
      name: nginx
      state: restarted
      enabled: yes
  - name: enable cron job for nginx cert renewel
    cron:
      name: "nginx cert renewel"
      miunte: "40"
      hour: "3"
      day: "0"
      job: "certbot renew >> /var/log/certbot-renew.log && /etc/init.d/nginx reload > /dev/null 2>&1"
